/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace EncryptedMessenger {
  export type MessageMetaStruct = {
    sender: PromiseOrValue<string>;
    recipient: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    contentHash: PromiseOrValue<BytesLike>;
    cid: PromiseOrValue<string>;
    keyCiphertext: PromiseOrValue<BytesLike>;
    signature: PromiseOrValue<BytesLike>;
  };

  export type MessageMetaStructOutput = [
    string,
    string,
    BigNumber,
    string,
    string,
    string,
    string
  ] & {
    sender: string;
    recipient: string;
    timestamp: BigNumber;
    contentHash: string;
    cid: string;
    keyCiphertext: string;
    signature: string;
  };
}

export interface EncryptedMessengerInterface extends utils.Interface {
  functions: {
    "computeCidHash(string)": FunctionFragment;
    "getInboxIds(address)": FunctionFragment;
    "getMessage(uint256)": FunctionFragment;
    "getSentIds(address)": FunctionFragment;
    "lastSentAt(address)": FunctionFragment;
    "maxPerMinute()": FunctionFragment;
    "minIntervalSecs()": FunctionFragment;
    "nextId()": FunctionFragment;
    "pubkeys(address)": FunctionFragment;
    "registerPublicKey(bytes32,string)": FunctionFragment;
    "sendMessage(address,bytes32,string,bytes,bytes)": FunctionFragment;
    "sentCountInWindow(address)": FunctionFragment;
    "verifySignature(uint256)": FunctionFragment;
    "windowStart(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "computeCidHash"
      | "getInboxIds"
      | "getMessage"
      | "getSentIds"
      | "lastSentAt"
      | "maxPerMinute"
      | "minIntervalSecs"
      | "nextId"
      | "pubkeys"
      | "registerPublicKey"
      | "sendMessage"
      | "sentCountInWindow"
      | "verifySignature"
      | "windowStart"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computeCidHash",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getInboxIds",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessage",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSentIds",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "lastSentAt",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPerMinute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minIntervalSecs",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pubkeys",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPublicKey",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sentCountInWindow",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySignature",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "windowStart",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeCidHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInboxIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSentIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastSentAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxPerMinute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minIntervalSecs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pubkeys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPublicKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentCountInWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "windowStart",
    data: BytesLike
  ): Result;

  events: {
    "MessageSent(uint256,address,address,bytes32,string,uint64)": EventFragment;
    "PublicKeyRegistered(address,bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MessageSent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PublicKeyRegistered"): EventFragment;
}

export interface MessageSentEventObject {
  id: BigNumber;
  from: string;
  to: string;
  contentHash: string;
  cid: string;
  timestamp: BigNumber;
}
export type MessageSentEvent = TypedEvent<
  [BigNumber, string, string, string, string, BigNumber],
  MessageSentEventObject
>;

export type MessageSentEventFilter = TypedEventFilter<MessageSentEvent>;

export interface PublicKeyRegisteredEventObject {
  user: string;
  pubKeyHash: string;
  pubKeyUri: string;
}
export type PublicKeyRegisteredEvent = TypedEvent<
  [string, string, string],
  PublicKeyRegisteredEventObject
>;

export type PublicKeyRegisteredEventFilter =
  TypedEventFilter<PublicKeyRegisteredEvent>;

export interface EncryptedMessenger extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EncryptedMessengerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    computeCidHash(
      cid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getInboxIds(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getMessage(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[EncryptedMessenger.MessageMetaStructOutput]>;

    getSentIds(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    lastSentAt(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    maxPerMinute(overrides?: CallOverrides): Promise<[BigNumber]>;

    minIntervalSecs(overrides?: CallOverrides): Promise<[BigNumber]>;

    nextId(overrides?: CallOverrides): Promise<[BigNumber]>;

    pubkeys(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { pubKeyHash: string; pubKeyUri: string }>;

    registerPublicKey(
      pubKeyHash: PromiseOrValue<BytesLike>,
      pubKeyUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendMessage(
      to: PromiseOrValue<string>,
      contentHash: PromiseOrValue<BytesLike>,
      cid: PromiseOrValue<string>,
      keyCiphertext: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sentCountInWindow(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    verifySignature(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    windowStart(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  computeCidHash(
    cid: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  getInboxIds(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getMessage(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<EncryptedMessenger.MessageMetaStructOutput>;

  getSentIds(
    user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  lastSentAt(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  maxPerMinute(overrides?: CallOverrides): Promise<BigNumber>;

  minIntervalSecs(overrides?: CallOverrides): Promise<BigNumber>;

  nextId(overrides?: CallOverrides): Promise<BigNumber>;

  pubkeys(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, string] & { pubKeyHash: string; pubKeyUri: string }>;

  registerPublicKey(
    pubKeyHash: PromiseOrValue<BytesLike>,
    pubKeyUri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendMessage(
    to: PromiseOrValue<string>,
    contentHash: PromiseOrValue<BytesLike>,
    cid: PromiseOrValue<string>,
    keyCiphertext: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sentCountInWindow(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  verifySignature(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  windowStart(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    computeCidHash(
      cid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    getInboxIds(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getMessage(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<EncryptedMessenger.MessageMetaStructOutput>;

    getSentIds(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    lastSentAt(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxPerMinute(overrides?: CallOverrides): Promise<BigNumber>;

    minIntervalSecs(overrides?: CallOverrides): Promise<BigNumber>;

    nextId(overrides?: CallOverrides): Promise<BigNumber>;

    pubkeys(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { pubKeyHash: string; pubKeyUri: string }>;

    registerPublicKey(
      pubKeyHash: PromiseOrValue<BytesLike>,
      pubKeyUri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    sendMessage(
      to: PromiseOrValue<string>,
      contentHash: PromiseOrValue<BytesLike>,
      cid: PromiseOrValue<string>,
      keyCiphertext: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sentCountInWindow(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifySignature(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    windowStart(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "MessageSent(uint256,address,address,bytes32,string,uint64)"(
      id?: PromiseOrValue<BigNumberish> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      contentHash?: null,
      cid?: null,
      timestamp?: null
    ): MessageSentEventFilter;
    MessageSent(
      id?: PromiseOrValue<BigNumberish> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      contentHash?: null,
      cid?: null,
      timestamp?: null
    ): MessageSentEventFilter;

    "PublicKeyRegistered(address,bytes32,string)"(
      user?: PromiseOrValue<string> | null,
      pubKeyHash?: null,
      pubKeyUri?: null
    ): PublicKeyRegisteredEventFilter;
    PublicKeyRegistered(
      user?: PromiseOrValue<string> | null,
      pubKeyHash?: null,
      pubKeyUri?: null
    ): PublicKeyRegisteredEventFilter;
  };

  estimateGas: {
    computeCidHash(
      cid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInboxIds(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMessage(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSentIds(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastSentAt(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxPerMinute(overrides?: CallOverrides): Promise<BigNumber>;

    minIntervalSecs(overrides?: CallOverrides): Promise<BigNumber>;

    nextId(overrides?: CallOverrides): Promise<BigNumber>;

    pubkeys(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerPublicKey(
      pubKeyHash: PromiseOrValue<BytesLike>,
      pubKeyUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendMessage(
      to: PromiseOrValue<string>,
      contentHash: PromiseOrValue<BytesLike>,
      cid: PromiseOrValue<string>,
      keyCiphertext: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sentCountInWindow(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifySignature(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    windowStart(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    computeCidHash(
      cid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInboxIds(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMessage(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSentIds(
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastSentAt(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxPerMinute(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minIntervalSecs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nextId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pubkeys(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerPublicKey(
      pubKeyHash: PromiseOrValue<BytesLike>,
      pubKeyUri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendMessage(
      to: PromiseOrValue<string>,
      contentHash: PromiseOrValue<BytesLike>,
      cid: PromiseOrValue<string>,
      keyCiphertext: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sentCountInWindow(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifySignature(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    windowStart(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
